[build]
  command = "python -m pip install -r requirements-build.txt && jupyter lite build --contents content --output-dir dist"
  publish = "dist"

[[headers]]
  for = "/*"

  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
